name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: DevOpsLookup/src/WebApp/package-lock.json

    - name: Install dependencies
      run: |
        cd DevOpsLookup/src/WebApp
        npm ci

    - name: Build
      run: |
        cd DevOpsLookup/src/WebApp
        npm run build

    - name: Test
      run: |
        cd DevOpsLookup/src/WebApp
        npm test -- --watchAll=false

  terraform-validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.0.0'
    
    - name: Terraform Init
      run: |
        cd DevOpsLookup/infrastructure
        terraform init -backend=false
    
    - name: Terraform Validate
      run: |
        cd DevOpsLookup/infrastructure
        terraform validate 